# Test against the latest version of this Node.js version
# environment:
# nodejs_version: "7.9.0 x64"

branches:
    only:
    - master
    - /^release.*/

platform:
    - x86
    - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 7.9.0
  # install modules
  - npm install -g npm@4
  - npm install

artifacts:
    - path: node_modules/vscode-ripgrep/bin/*.exe
      name: RpGrepExe

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

build: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
